services:
  db-stats:
    image: postgres:16
    container_name: db-stats
    environment:
      POSTGRES_DB: ewm_stats
      POSTGRES_USER: ewm
      POSTGRES_PASSWORD: ewm
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ewm -d ewm_stats"]
      interval: 5s
      timeout: 3s
      retries: 10

  stats-server:
    build:
      context: .
      dockerfile: statistics/ewm-stats-server/Dockerfile
    depends_on:
      db-stats:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-stats:5432/ewm_stats
      SPRING_DATASOURCE_USERNAME: ewm
      SPRING_DATASOURCE_PASSWORD: ewm
      SERVER_PORT: 9090
    ports:
      - "9090:9090"

  main-service:
    build:
      context: .
      dockerfile: statistics/ewm-main-service/Dockerfile
    depends_on:
      - stats-server
    environment:
      SERVER_PORT: 8080
      STATS_BASE_URL: http://stats-server:9090
    ports:
      - "8080:8080"