services:
  stats-db:
    image: postgres:15.4
    container_name: stats-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ewm_stats
      POSTGRES_USER: ewm
      POSTGRES_PASSWORD: ewm
    ports:
      - "5433:5432"
    volumes:
      - pg-stats-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ewm -d ewm_stats" ]
      interval: 5s
      timeout: 3s
      retries: 30

  stats-server:
    build:
      context: .
      dockerfile: statistics/ewm-stats-server/Dockerfile
    container_name: stats-server
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/ewm_stats
      SPRING_DATASOURCE_USERNAME: ewm
      SPRING_DATASOURCE_PASSWORD: ewm
      SERVER_PORT: "9090"
    ports:
      - "9090:9090"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:9090/actuator/health | grep -q UP || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s

volumes:
  pg-stats-data: { }