services:
  stats-db:
    image: postgres:15.4
    environment:
      POSTGRES_DB: ewm_stats
      POSTGRES_USER: ewm
      POSTGRES_PASSWORD: ewm
    ports:
      - "5433:5432"
    volumes:
      - pg-stats-data:/var/lib/postgresql/data

  stats-server:
    build: ./statistics/ewm-stats-server
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/ewm_stats
      SPRING_DATASOURCE_USERNAME: ewm
      SPRING_DATASOURCE_PASSWORD: ewm
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "9090:9090"

volumes:
  pg-stats-data: {}